package tech.minesoft.minetv.v3app.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import tech.minesoft.minetv.v3app.bean.MineMeta;
import tech.minesoft.minetv.v3app.bean.MineMovieInfo;
import tech.minesoft.minetv.v3app.bean.MineSiteInfo;
import tech.minesoft.minetv.v3app.bean.MineViewInfo;

import tech.minesoft.minetv.v3app.greendao.MineMetaDao;
import tech.minesoft.minetv.v3app.greendao.MineMovieInfoDao;
import tech.minesoft.minetv.v3app.greendao.MineSiteInfoDao;
import tech.minesoft.minetv.v3app.greendao.MineViewInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mineMetaDaoConfig;
    private final DaoConfig mineMovieInfoDaoConfig;
    private final DaoConfig mineSiteInfoDaoConfig;
    private final DaoConfig mineViewInfoDaoConfig;

    private final MineMetaDao mineMetaDao;
    private final MineMovieInfoDao mineMovieInfoDao;
    private final MineSiteInfoDao mineSiteInfoDao;
    private final MineViewInfoDao mineViewInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mineMetaDaoConfig = daoConfigMap.get(MineMetaDao.class).clone();
        mineMetaDaoConfig.initIdentityScope(type);

        mineMovieInfoDaoConfig = daoConfigMap.get(MineMovieInfoDao.class).clone();
        mineMovieInfoDaoConfig.initIdentityScope(type);

        mineSiteInfoDaoConfig = daoConfigMap.get(MineSiteInfoDao.class).clone();
        mineSiteInfoDaoConfig.initIdentityScope(type);

        mineViewInfoDaoConfig = daoConfigMap.get(MineViewInfoDao.class).clone();
        mineViewInfoDaoConfig.initIdentityScope(type);

        mineMetaDao = new MineMetaDao(mineMetaDaoConfig, this);
        mineMovieInfoDao = new MineMovieInfoDao(mineMovieInfoDaoConfig, this);
        mineSiteInfoDao = new MineSiteInfoDao(mineSiteInfoDaoConfig, this);
        mineViewInfoDao = new MineViewInfoDao(mineViewInfoDaoConfig, this);

        registerDao(MineMeta.class, mineMetaDao);
        registerDao(MineMovieInfo.class, mineMovieInfoDao);
        registerDao(MineSiteInfo.class, mineSiteInfoDao);
        registerDao(MineViewInfo.class, mineViewInfoDao);
    }
    
    public void clear() {
        mineMetaDaoConfig.clearIdentityScope();
        mineMovieInfoDaoConfig.clearIdentityScope();
        mineSiteInfoDaoConfig.clearIdentityScope();
        mineViewInfoDaoConfig.clearIdentityScope();
    }

    public MineMetaDao getMineMetaDao() {
        return mineMetaDao;
    }

    public MineMovieInfoDao getMineMovieInfoDao() {
        return mineMovieInfoDao;
    }

    public MineSiteInfoDao getMineSiteInfoDao() {
        return mineSiteInfoDao;
    }

    public MineViewInfoDao getMineViewInfoDao() {
        return mineViewInfoDao;
    }

}
